name: Windows 10 Chrome Remote Desktop

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Chrome Remote Desktop
      run: |
        $ChromeRemoteDesktopURL = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        $OutputPath = "chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri $ChromeRemoteDesktopURL -OutFile $OutputPath

    - name: Install Chrome Remote Desktop
      run: Start-Process msiexec.exe -ArgumentList "/i chromeremotedesktophost.msi /qn /norestart /l*v install.log INSTALLDIR=C:\Custom\ChromeRemoteDesktop" -Wait
      shell: powershell

    - name: List files and folders in installation folder
      run: |
        $ChromeRemoteDesktopPath = "C:\Custom\ChromeRemoteDesktop"
        Get-ChildItem -Path $ChromeRemoteDesktopPath -Recurse | Select-Object -Property FullName
      shell: powershell

    - name: Set up Chrome Remote Desktop
      run: |
        $RemotingStartPath = Join-Path -Path $ChromeRemoteDesktopPath -ChildPath "remoting_start.exe"
        & "$RemotingStartPath" --code="${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$env:COMPUTERNAME
      shell: powershell
      env:
        CHROME_REMOTE_DESKTOP_CODE: ${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set up user authentication
      run: |
        $password = ConvertTo-SecureString "@cyb3rking" -AsPlainText -Force
        New-LocalUser -Name "runneradmin" -Password $password -FullName "Runner Admin" -Description "GitHub Actions Runner Admin"
