on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download and Install Chrome Remote Desktop
      run: |
        $URL = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        $OutputPath = "$env:TEMP\chromeremotedesktophost.msi"
        bitsadmin /transfer ChromeRemoteDesktopDownload /download /priority normal $URL $OutputPath
        Start-Process msiexec.exe -ArgumentList "/i $OutputPath /qn /norestart" -Wait -NoNewWindow
      shell: powershell

    - name: Set up Chrome Remote Desktop
      run: |
        $Path = "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        if (-not (Test-Path $Path)) {
          Write-Error "Could not find remoting_start_host.exe at expected location: $Path"
          exit 1
        }

        # Load Windows Forms assembly for SendKeys
        Add-Type -AssemblyName System.Windows.Forms

        # Start the process
        $process = Start-Process $Path -ArgumentList "--code=${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}", "--redirect-url=https://remotedesktop.google.com/_/oauthredirect", "--name=$env:COMPUTERNAME" -PassThru

        # Wait a bit for the PIN prompt
        Start-Sleep -Seconds 5

        # Send PIN (replace 123456 with your desired PIN)
        [System.Windows.Forms.SendKeys]::SendWait('123456{ENTER}')

        # Wait again for potential confirmation
        Start-Sleep -Seconds 2

        # Send PIN again to confirm
        [System.Windows.Forms.SendKeys]::SendWait('123456{ENTER}')

        # Wait for the process to exit
        $process.WaitForExit()

        if ($process.ExitCode -ne 0) {
          Write-Error "Chrome Remote Desktop setup failed with exit code: $($process.ExitCode)"
          exit 1
        }
      shell: powershell
      env:
        CHROME_REMOTE_DESKTOP_CODE: ${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      shell: powershell
