on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download and Install Chrome Remote Desktop
      run: |
        $URL = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        $OutputPath = "$env:TEMP\chromeremotedesktophost.msi"
        bitsadmin /transfer ChromeRemoteDesktopDownload /download /priority normal $URL $OutputPath
        Start-Process msiexec.exe -ArgumentList "/i $OutputPath /qn /norestart" -Wait -NoNewWindow
      shell: powershell

    - name: Set up Chrome Remote Desktop
      run: |
        $Path = "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        if (-not (Test-Path $Path)) {
          Write-Error "Could not find remoting_start_host.exe at expected location: $Path"
          exit 1
        }

        Add-Type -AssemblyName System.Windows.Forms

        $process = Start-Process $Path -ArgumentList "--code=${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}", "--redirect-url=https://remotedesktop.google.com/_/oauthredirect", "--name=$env:COMPUTERNAME" -PassThru

        Start-Sleep -Seconds 5
        [System.Windows.Forms.SendKeys]::SendWait('123456{ENTER}')
        Start-Sleep -Seconds 2
        [System.Windows.Forms.SendKeys]::SendWait('123456{ENTER}')

        $process.WaitForExit()

        if ($process.ExitCode -ne 0) {
          Write-Error "Chrome Remote Desktop setup failed with exit code: $($process.ExitCode)"
          exit 1
        }
      shell: powershell
      env:
        CHROME_REMOTE_DESKTOP_CODE: ${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}

    - name: Configure and Start Chrome Remote Desktop Service
      run: |
        $serviceName = "chromoting"
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service -eq $null) {
          Write-Error "Chrome Remote Desktop service not found"
          exit 1
        }
        
        Set-Service -Name $serviceName -StartupType Automatic
        Start-Service -Name $serviceName
        
        $status = (Get-Service -Name $serviceName).Status
        Write-Output "Chrome Remote Desktop service status: $status"
        
        if ($status -ne "Running") {
          Write-Error "Failed to start Chrome Remote Desktop service"
          exit 1
        }
      shell: powershell

    - name: Enable Remote Desktop and Configure Firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
        New-NetFirewallRule -DisplayName "Chrome Remote Desktop" -Direction Inbound -Program "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_host.exe" -Action Allow
      shell: powershell

    - name: Display Network Information
      run: |
        ipconfig /all
        netstat -ano | findstr :3389
      shell: powershell
